feat: cache deps for faster tests (#70)
* feat: cache deps for faster tests

Cache the cargo registry and build folder to speed up test times

* feat: cache by rust version

* more specific cache titles

* fix clippy lints installation error

diff --git a/.github/workflows/clippy-check.yml b/.github/workflows/clippy-check.yml
--- a/.github/workflows/clippy-check.yml
+++ b/.github/workflows/clippy-check.yml
@@ -1,5 +1,7 @@
 on: [pull_request]
 name: Clippy
+env:
+  RUST_VERSION: nightly-2022-09-13
 jobs:
   clippy_check:
     runs-on: ubuntu-latest
@@ -8,20 +10,29 @@ jobs:
       - uses: actions-rs/toolchain@v1
         with:
           components: clippy, rustfmt
-          toolchain: nightly-2022-09-13
+          toolchain: ${{ env.RUST_VERSION }}
           override: true
+      - name: Cache packages
+        id: cache-cargo
+        uses: actions/cache@v3
+        with:
+          path: |
+            ~/.cargo/bin/
+            ~/.cargo/registry/index/
+            ~/.cargo/registry/cache/
+            ~/.cargo/git/db/
+            target/
+          key: ${{ runner.os }}-cargo-${{ env.RUST_VERSION }}-${{ hashFiles('**/Cargo.lock') }}-clippy
+          restore-keys: |
+            ${{ runner.os }}-cargo-${{ env.RUST_VERSION }}-${{ hashFiles('**/Cargo.lock') }}
+            ${{ runner.os }}-cargo-${{ env.RUST_VERSION }}
       - uses: actions-rs/cargo@v1
         with:
           command: fmt
-          toolchain: nightly-2022-09-13
+          toolchain: ${{ env.RUST_VERSION }}
           args: --all -- --check
       - name: Install cargo-lints
-        uses: actions-rs/cargo@v1
-        with:
-          command: install
-          args: cargo-lints
+        # Cargo lints is most likely already installed in the cache, so || true to prevent failure
+        run: cargo install cargo-lints || true
       - name: Clippy lints
-        uses: actions-rs/cargo@v1
-        with:
-          command: lints
-          args: clippy --all-targets
+        run: cargo lints clippy --all-targets
