fix clippy lints installation error

diff --git a/.github/workflows/clippy-check.yml b/.github/workflows/clippy-check.yml
--- a/.github/workflows/clippy-check.yml
+++ b/.github/workflows/clippy-check.yml
@@ -33,12 +33,7 @@ jobs:
           toolchain: ${{ env.RUST_VERSION }}
           args: --all -- --check
       - name: Install cargo-lints
-        uses: actions-rs/cargo@v1
-        with:
-          command: install
-          args: cargo-lints
+        # Cargo lints is most likely already installed in the cache, so || true to prevent failure
+        run: cargo install cargo-lints || true
       - name: Clippy lints
-        uses: actions-rs/cargo@v1
-        with:
-          command: lints
-          args: clippy --all-targets
+        run: cargo lints clippy --all-targets
